version: '3.8'
services:
  lane_fusion_dev:
    image: lidarprojectiondev
    volumes:
      - ./:/workspace/lane_fusion
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/ros/noetic:/opt/ros/noetic:ro
    environment:
      - DISPLAY=\${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://host.docker.internal:11311
      - ROS_HOSTNAME=lane_fusion_container
    network_mode: "host"
    privileged: true
    working_dir: /workspace/lane_fusion
    command: bash -c "source /opt/ros/noetic/setup.bash && exec bash"
    # Modern GPU access specification
    device_requests:
      - capabilities: [gpu]